import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import styles from "./globals.module.css";
import Sidebar from "../../../components/Sidebar";
import SearchBar from "../../../components/SearchBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Summarist Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Sidebar />
        <SearchBar />
        <main
          className={`${geistSans.variable} ${geistMono.variable} ${styles.main__content}`}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
